#!/usr/bin/env bash
# Regenerate the Swift constant that embeds weights-manifest.json (#163).
#
# Why this exists: the manifest used to ship as a SwiftPM resource bundle, which
# means a `bestasr_BestASRKit.bundle` had to sit next to the executable. No
# install path ever put it there — `scripts/install.sh` copies only the binaries
# and the release uploads only the binary — so `Bundle.module` hit
# `Swift.fatalError` and the process died with SIGTRAP. The manifest is a
# version-pinned static table, so it belongs *in* the binary.
#
# weights-manifest.json stays the human-edited source of truth. Run this after
# editing it; WeightVerifierTests fails if the two drift.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
src="$repo_root/Sources/BestASRKit/Supply/weights-manifest.json"
out="$repo_root/Sources/BestASRKit/Supply/WeightsManifestEmbedded.swift"

[ -f "$src" ] || { echo "missing $src" >&2; exit 1; }
jq empty "$src" || { echo "$src is not valid JSON" >&2; exit 1; }

{
    cat <<'HEADER'
// Generated by scripts/embed-weights-manifest.sh — DO NOT EDIT BY HAND.
//
// Source of truth: Sources/BestASRKit/Supply/weights-manifest.json
// Regenerate after editing that file. `EmbeddedWeightsManifestTests` fails if
// this copy drifts from it.
//
// This is embedded rather than shipped as a SwiftPM resource because a bare
// installed binary has no side-car bundle for `Bundle.module` to find (#163).

extension WeightVerifier {
    /// The pinned-weights manifest, compiled into the binary.
    public static let embeddedManifestJSON = #"""
HEADER
    jq --indent 2 -S . "$src" | sed 's/^/        /'
    cat <<'FOOTER'
        """#
}
FOOTER
} > "$out"

echo "wrote $out ($(wc -c < "$out" | tr -d ' ') bytes)"
